name: multiline 

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: verifying repository
              uses: actions/checkout@v4
            - name: list and read files
              run: |
                echo "welcome to github actions"
                ls -ltra 
                cat README.md
            - name: generate ASCII artwork
              run: cowsay -f dragon "run for cover,Iam a DRAGON.....RAWR" >> dragon.txt
        